[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [ "arm-none-eabi-gdb","-iex","targ ext /dev/ttyACM0","-iex","mon swdp","-iex","att 1", "-iex","mon rtt", "-ex", "load" ]
#runner = "probe-rs run --chip RP235x"
#runner = "elf2uf2-rs -d"
#runner = "picotool load -u -v -x -t elf"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "debug"
